repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      language_version: python3.6
      args: ["--exclude ext-libs", "-l 120"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7  # pick a git hash / tag to point to
    hooks:
    -   id: flake8