matrix:
  include:
    - language: python
      python: 3.6
      dist: xenial
      sudo: true
      branches:
        only:
        - master-qgis3
        - dev-qgis3
      services:
        - docker
      before_install:
        - pip install flake8 mypy
        - flake8 plugin
      install:
          - cd docker && docker-compose up -d
          - sleep 10 # This is required to allow xvfb to start
      script:
          - docker exec -it qgis3 sh -c "qgis_testrunner.sh tests_directory"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_deploy:
        - zip -r tmp.zip ext-libs/ sample_data/koh-samui_thailand.mbtiles sample_data/metadata.json ui/ util/ metadata.txt README.md *.py -x ext-libs/mapboxstyle2qgis/sample_data\* ext-libs/mapboxstyle2qgis/tests\* ext-libs/mapboxstyle2qgis/.* \*.pyc \*/__pycache__\* \*.ui \*.bat
        - unzip tmp.zip -d vector_tiles_reader
        - zip -r Vector-Tiles-Reader-${TRAVIS_TAG}.zip vector_tiles_reader
        - rm -rf vector_tiles_reader
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: Vector-Tiles-Reader-${TRAVIS_TAG}.zip
        skip_cleanup: true
        draft: true
        on:
          tags: true
          branch: master

    - language: cpp
      branches:
          only:
          - develop
      os:
        - linux
      compiler:
        - gcc
        - clang
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install gcc-multilib g++-multilib -y
      script:
        - git clone https://github.com/mapbox/protozero.git ../protozero
        - git clone https://github.com/mapbox/vtzero.git ../vtzero
        - cd ../vtzero
        - git submodule update --init
        - cd $TRAVIS_BUILD_DIR/ext-libs/pbf2geojson
        - sudo rm *.so && sudo rm *.dll && cd ../..
        - make linux
        - cd ..
        - docker run --rm dockcross/windows-x64 > ./dockcross-windows-x64 && chmod +x ./dockcross-windows-x64
        - docker run --rm dockcross/windows-x86 > ./dockcross-windows-x86 && chmod +x ./dockcross-windows-x86
        - ./dockcross-windows-x64 sh -c "cd Vector-Tiles-Reader-QGIS-Plugin && make windows64_dockcross"
        - ./dockcross-windows-x86 sh -c "cd Vector-Tiles-Reader-QGIS-Plugin && make windows32_dockcross"

    - language: cpp
      branches:
          only:
          - develop
      os:
        - osx
      compiler:
        - gcc
      script:
        - git clone https://github.com/mapbox/protozero.git ../protozero
        - git clone https://github.com/mapbox/vtzero.git ../vtzero
        - cd ../vtzero
        - git submodule update --init
        - cd $TRAVIS_BUILD_DIR/ext-libs/pbf2geojson
        - sudo rm *.so && sudo rm *.dll && cd ../..
        - make osx

notifications:
    on_success: never # default: change
    on_failure: always # default: always

