matrix:
  allow_failures:
    - os: osx
  include:
    - language: python
      sudo: required
      python: '2.7'
      services:
        - docker
      before_install:
        - docker-compose build
      install:
        - docker-compose run -d --name qgis2 qgis2
        - sleep 10
      script:
        - docker exec -it qgis2 sh -c "qgis_testrunner.sh vector_tiles_reader.tests.test_all"
      after_success:
        - docker exec -it qgis2 sh -c "cd vector-tiles-reader && export COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN && coveralls"

    - language: cpp
      os:
        - linux
        - osx
      compiler:
        - gcc
        - clang
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install gcc-multilib g++-multilib -y
      script:
        - git clone https://github.com/mapbox/protozero.git ../protozero
        - git clone https://github.com/mapbox/vtzero.git ../vtzero
        - cd ../vtzero
        - git submodule update --init
        - cd $TRAVIS_BUILD_DIR
        - make linux
        - make osx
      after_success:
        - cd $TRAVIS_BUILD_DIR
        #git -c user.name='travis' -c user.email='travis' commit -m init
        # Make sure to make the output quiet, or else the API token will leak!
        # This works because the API key can replace your password.
        - git checkout develop
        - git commit -m "native pbf2geojson update" ext-libs/pbf2geojson/*.so
        - git push --dry-run -q https://mnboos:$GITHUB_TOKEN@github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin &2>/dev/null

notifications:
    on_success: never # default: change
    on_failure: always # default: always

