matrix:
  allow_failures:
    - os: osx
  include:
    - language: python
      sudo: required
      python: '2.7'
      branches:
        only:
        - master
        - develop
      services:
        - docker
      before_install:
        - docker-compose build
      install:
        - docker-compose run -d --name qgis2 qgis2
        - sleep 10
      script:
        - docker exec -it qgis2 sh -c "qgis_testrunner.sh vector_tiles_reader.tests.test_all"
      after_success:
        - docker exec -it qgis2 sh -c "cd vector-tiles-reader && export COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN && coveralls"

    - language: cpp
      branches:
          only:
          - master
          - develop
      os:
        - linux
        - osx
      compiler:
        - gcc
        - clang
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install gcc-multilib g++-multilib -y
      script:
        - git clone https://github.com/mapbox/protozero.git ../protozero
        - git clone https://github.com/mapbox/vtzero.git ../vtzero
        - cd ../vtzero
        - git submodule update --init
        - cd $TRAVIS_BUILD_DIR
        - make linux
        - make osx
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        target_branch: pbf2geojson_travis_auto_build
        local_dir: $TRAVIS_BUILD_DIR/ext-libs/pbf2geojson
        on:
          branch: develop

notifications:
    on_success: never # default: change
    on_failure: always # default: always

