matrix:
  allow_failures:
    - os: osx
  include:
    - language: python
      sudo: required
      python: '2.7'
      services:
        - docker
      before_install:
#        - docker pull mnboos/qgis-testing-environment:release-2_18
        - docker-compose build
      install:
#        - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 mnboos/qgis-testing-environment:release-2_18
        - docker-compose run -d --name qgis2 qgis2
        - sleep 10
        # Setup qgis and enable the plugin
#        - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh vector_tiles_reader"
        # If needd additional steps (for example make or paver setup, place it here)
        # Link the plugin to the tests_directory
#        - docker exec -it qgis-testing-environment sh -c "rm -rf /root/.qgis2/python/plugins/vector_tiles_reader"
#        - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory /root/.qgis2/python/plugins/vector_tiles_reader"
#        - docker exec -it qgis-testing-environment sh -c "pip install coverage"
      script:
#        - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh vector_tiles_reader.tests.test_all"
        - docker exec -it qgis2 sh -c "qgis_testrunner.sh vector_tiles_reader.tests.test_vtreader"
        - docker exec -it qgis2 sh -c "cd vector-tiles-reader && coveralls"

    - language: cpp
      os:
      - linux
      - osx
      compiler:
        - gcc
        - clang
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install gcc-multilib g++-multilib -y
      script:
      - git clone https://github.com/mapbox/protozero.git ../protozero
      - git clone https://github.com/mapbox/vtzero.git ../vtzero
      - cd ../vtzero
      - git submodule update --init
      - cd $TRAVIS_BUILD_DIR
      - make linux
      - make osx

notifications:
    on_success: never # default: change
    on_failure: always # default: always

