matrix:
  allow_failures:
    - os: osx
  include:
    - language: python
      sudo: required
      python: '2.7'
      services:
        - docker
      before_install:
        # Build this docker:
#        - git clone https://github.com/boundlessgeo/qgis-testing-environment-docker.git qgis-testing-environment
#        - cd qgis-testing-environment
#        - |
#          docker build -t qgis-testing-environment \
#          --build-arg QGIS_REPOSITORY='https://github.com/qgis/QGIS.git' \
#          --build-arg QGIS_BRANCH='release-2_18' \
#          --build-arg LEGACY='true' .
        # or just pull it:
       #- docker pull mnboos/qgis-testing-environment:release-2_18
        - docker-compose build
      install:
        #- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 mnboos/qgis-testing-environment:release-2_18
        - docker-compose run -d --name qgis2
        - sleep 10
        # Setup qgis and enable the plugin
        #- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh vector_tiles_reader"
        # If needd additional steps (for example make or paver setup, place it here)
        # Link the plugin to the tests_directory
        #- docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory /root/.qgis2/python/plugins/vector_tiles_reader"
      script:
        - docker exec -it qgis2 sh -c "qgis_testrunner.sh vector_tiles_reader.tests.test_vtreader"

    - language: cpp
      os:
      - linux
      - osx
      compiler:
        - gcc
        - clang
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install gcc-multilib g++-multilib -y
      script:
      - git clone https://github.com/mapbox/protozero.git ../protozero
      - git clone https://github.com/mapbox/vtzero.git ../vtzero
      - cd ../vtzero
      - git submodule update --init
      - cd $TRAVIS_BUILD_DIR
      - make linux
      - make osx

notifications:
    on_success: never # default: change
    on_failure: always # default: always

