# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source

version: '3'

services:
  qgis2:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TAG: "release-2_18"
        QGIS_PLUGINS_DIR: "/root/.qgis2/python/plugins"
    volumes:
      - .:/vector-tiles-reader
      - .:/tests_directory
#  qgis-latest:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#      args:
#        QGIS_BRANCH: "master"
#    volumes:
#      - ./:/vector-tiles-reader