# The contents of this file are subject to the license and copyright
# detailed in the LICENSE and NOTICE files at the root of the source

version: '3'

services:
  qgis2:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TAG: "release-2_18"
        QGIS_PLUGINS_DIR: "/root/.qgis2/python/plugins"
    volumes:
      - .:/vector-tiles-reader
      - .:/tests_directory
  qgis3:
    build:
      context: ./
      dockerfile: DockerfileQGIS3
      args:
        QGIS_PLUGINS_DIR: "/root/.local/share/QGIS/QGIS3/profiles/default"
    volumes:
      - .:/vector-tiles-reader
      - .:/tests_directory